vayu: startBuild: Do not supply host variables
Some users may only target cross targets like ARM and AArch64, meaning
we cannot generate X86 code on an x86_64 host:

  HOSTCC  scripts/basic/fixdep
  GEN     Makefile
error: unable to create target: 'No available targets are compatible
with triple "x86_64-unknown-linux-gnu"'
1 error generated.
make[3]: *** [scripts/Makefile.host:92: scripts/basic/fixdep] Error 1

Just remove the HOST{CC,LD} variables so that we don't cause a build
error, the host tools are a minor part of the build process so we don't
lose out on any PGO coverage this way.

Signed-off-by: XSans02 <xsans966@gmail.com>